// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzEwlq6hf4JC_uJ1gMob4gIsE6ebCEr7o',
    appId: '1:487095788331:web:4a8d99462edaaec0e95b6e',
    messagingSenderId: '487095788331',
    projectId: 'chat-app-cd1a6',
    authDomain: 'chat-app-cd1a6.firebaseapp.com',
    storageBucket: 'chat-app-cd1a6.appspot.com',
    measurementId: 'G-CTCRGBN3T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKppGDK2CgnTI7MJzraWdWyMZKfVijvCo',
    appId: '1:487095788331:android:c860a970003fa03ee95b6e',
    messagingSenderId: '487095788331',
    projectId: 'chat-app-cd1a6',
    storageBucket: 'chat-app-cd1a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGrmPEfu8dwoqsyoJfW64Wn_hp2zdoFo',
    appId: '1:487095788331:ios:d296f504fcd4aa48e95b6e',
    messagingSenderId: '487095788331',
    projectId: 'chat-app-cd1a6',
    storageBucket: 'chat-app-cd1a6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgGrmPEfu8dwoqsyoJfW64Wn_hp2zdoFo',
    appId: '1:487095788331:ios:b74b6f03e60afbd7e95b6e',
    messagingSenderId: '487095788331',
    projectId: 'chat-app-cd1a6',
    storageBucket: 'chat-app-cd1a6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
